# Generated by Django 4.2.5 on 2023-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormfirstapp', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
